services:
    angular-docker:
        container_name: frontend
        build: .
        ports:
            - '9000:80'

networks:
    default:
        name: "marketplace-network"
        external: true
